# Generated by Django 5.1.15 on 2026-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
