# Generated by Django 5.1.15 on 2026-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gradient',
            field=models.CharField(blank=True, default='', help_text='CSS background value used on service cards, e.g. var(--gradient-blush)', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text='List of short bullet strings describing what is included'),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
