# Generated by Django 5.1.15 on 2026-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='concern',
            field=models.CharField(blank=True, default='', help_text='e.g. Repair, Hydration, Brightening', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=list, help_text='List of short bullet strings shown on the product page'),
        ),
        migrations.AddField(
            model_name='product',
            name='gradient',
            field=models.CharField(blank=True, default='', help_text='CSS background value used on product cards, e.g. var(--gradient-blush)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', help_text='Display pack size, e.g. 50ml', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
